# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from loockit.api import sesame_pb2 as sesame__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sesame_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SesameServiceStub(object):
    """Control and observe SESAME4 / SESAME Bot1 devices.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/sesame.SesameService/ListDevices',
                request_serializer=sesame__pb2.Empty.SerializeToString,
                response_deserializer=sesame__pb2.DeviceList.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/sesame.SesameService/GetStatus',
                request_serializer=sesame__pb2.DeviceRef.SerializeToString,
                response_deserializer=sesame__pb2.DeviceState.FromString,
                _registered_method=True)
        self.Lock = channel.unary_unary(
                '/sesame.SesameService/Lock',
                request_serializer=sesame__pb2.CommandRequest.SerializeToString,
                response_deserializer=sesame__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Unlock = channel.unary_unary(
                '/sesame.SesameService/Unlock',
                request_serializer=sesame__pb2.CommandRequest.SerializeToString,
                response_deserializer=sesame__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Toggle = channel.unary_unary(
                '/sesame.SesameService/Toggle',
                request_serializer=sesame__pb2.CommandRequest.SerializeToString,
                response_deserializer=sesame__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Click = channel.unary_unary(
                '/sesame.SesameService/Click',
                request_serializer=sesame__pb2.CommandRequest.SerializeToString,
                response_deserializer=sesame__pb2.CommandResult.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/sesame.SesameService/StreamStatus',
                request_serializer=sesame__pb2.StreamRequest.SerializeToString,
                response_deserializer=sesame__pb2.DeviceState.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/sesame.SesameService/GetHistory',
                request_serializer=sesame__pb2.HistoryRequest.SerializeToString,
                response_deserializer=sesame__pb2.HistoryList.FromString,
                _registered_method=True)


class SesameServiceServicer(object):
    """Control and observe SESAME4 / SESAME Bot1 devices.
    """

    def ListDevices(self, request, context):
        """List all configured devices and their last known state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get the last known state of a single device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lock(self, request, context):
        """Lock / Unlock / Toggle apply to SESAME4 (a lock).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Toggle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Click(self, request, context):
        """Click applies to SESAME Bot1 (a button pusher).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Server-streaming real-time state updates. Optionally filter by device id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Operation history / persisted state changes (requires history enabled).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SesameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=sesame__pb2.Empty.FromString,
                    response_serializer=sesame__pb2.DeviceList.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=sesame__pb2.DeviceRef.FromString,
                    response_serializer=sesame__pb2.DeviceState.SerializeToString,
            ),
            'Lock': grpc.unary_unary_rpc_method_handler(
                    servicer.Lock,
                    request_deserializer=sesame__pb2.CommandRequest.FromString,
                    response_serializer=sesame__pb2.CommandResult.SerializeToString,
            ),
            'Unlock': grpc.unary_unary_rpc_method_handler(
                    servicer.Unlock,
                    request_deserializer=sesame__pb2.CommandRequest.FromString,
                    response_serializer=sesame__pb2.CommandResult.SerializeToString,
            ),
            'Toggle': grpc.unary_unary_rpc_method_handler(
                    servicer.Toggle,
                    request_deserializer=sesame__pb2.CommandRequest.FromString,
                    response_serializer=sesame__pb2.CommandResult.SerializeToString,
            ),
            'Click': grpc.unary_unary_rpc_method_handler(
                    servicer.Click,
                    request_deserializer=sesame__pb2.CommandRequest.FromString,
                    response_serializer=sesame__pb2.CommandResult.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=sesame__pb2.StreamRequest.FromString,
                    response_serializer=sesame__pb2.DeviceState.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=sesame__pb2.HistoryRequest.FromString,
                    response_serializer=sesame__pb2.HistoryList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sesame.SesameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sesame.SesameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SesameService(object):
    """Control and observe SESAME4 / SESAME Bot1 devices.
    """

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sesame.SesameService/ListDevices',
            sesame__pb2.Empty.SerializeToString,
            sesame__pb2.DeviceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sesame.SesameService/GetStatus',
            sesame__pb2.DeviceRef.SerializeToString,
            sesame__pb2.DeviceState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sesame.SesameService/Lock',
            sesame__pb2.CommandRequest.SerializeToString,
            sesame__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sesame.SesameService/Unlock',
            sesame__pb2.CommandRequest.SerializeToString,
            sesame__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Toggle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sesame.SesameService/Toggle',
            sesame__pb2.CommandRequest.SerializeToString,
            sesame__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Click(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sesame.SesameService/Click',
            sesame__pb2.CommandRequest.SerializeToString,
            sesame__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sesame.SesameService/StreamStatus',
            sesame__pb2.StreamRequest.SerializeToString,
            sesame__pb2.DeviceState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sesame.SesameService/GetHistory',
            sesame__pb2.HistoryRequest.SerializeToString,
            sesame__pb2.HistoryList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
